
import os
import torch
import numpy as np
import hashlib
import tempfile
import subprocess
from pathlib import Path
from torch.utils.data import TensorDataset
from tqdm import tqdm
import time

LKH_PATH = Path(__file__).parent.parent / "LKH-3.0.13/LKH"

def write_tsplib_euc2d(path, coords_int, name="inst"):
    """
    coords_int: (n,2) int array
    """
    n = coords_int.shape[0]
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"NAME : {name}\n")
        f.write("TYPE : TSP\n")
        f.write(f"DIMENSION : {n}\n")
        f.write("EDGE_WEIGHT_TYPE : EUC_2D\n")
        f.write("NODE_COORD_SECTION\n")
        for i, (x, y) in enumerate(coords_int, start=1):
            f.write(f"{i} {int(x)} {int(y)}\n")
        f.write("EOF\n")

def write_lkh_par(path, tsp_path, out_path, lkh_runs=1, seed=1234, time_limit=None):
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"PROBLEM_FILE = {tsp_path}\n")
        f.write(f"OUTPUT_TOUR_FILE = {out_path}\n")
        f.write(f"RUNS = {lkh_runs}\n")
        f.write(f"SEED = {seed}\n")
        if time_limit is not None:
            f.write(f"TIME_LIMIT = {time_limit}\n")
        # f.write("TRACE_LEVEL = 0\n")  # less logging

def read_tour_file(tour_path):
    """
    Returns tour as 0-based list of node indices (length n)
    """
    tour = []
    in_section = False
    try:
        with open(tour_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line == "TOUR_SECTION":
                    in_section = True
                    continue
                if not in_section:
                    continue
                if line == "-1" or line == "EOF":
                    break
                tour.append(int(line) - 1)  # to 0-based
    except FileNotFoundError:
        return None
    return tour

def solve_with_lkh(coords, runs=1, seed=1234, scale=1000000, time_limit=None):
    """
    Solve TSP using LKH.
    coords: (n, 2) numpy array
    """
    if not LKH_PATH.exists():
        raise FileNotFoundError(f"LKH solver not found at {LKH_PATH}")
        
    coords_int = np.rint(coords * scale).astype(np.int64)

    with tempfile.TemporaryDirectory() as td:
        tsp_path  = os.path.join(td, "inst.tsp")
        par_path  = os.path.join(td, "inst.par")
        tour_path = os.path.join(td, "inst.tour")

        write_tsplib_euc2d(tsp_path, coords_int, name="inst")
        write_lkh_par(par_path, tsp_path, tour_path, lkh_runs=runs, seed=seed, time_limit=time_limit)

        # Run LKH
        subprocess.run([str(LKH_PATH), par_path], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        tour = read_tour_file(tour_path)
        if tour is None:
            # Fallback or error
            return float('inf')
            
        # Calc cost based on original coords (or int?)
        # Standard: use what we gave to LKH? No, we gave int scaled.
        # But we usually evaluate with float euc2d on original unit square for training/val comparison?
        # In tsp/test.ipynb:
        # cost = np.sum(np.linalg.norm(coords_np[tour] - coords_np[np.roll(tour, -1)], axis=1))
        # This uses float coords. We want to be consistent with infer_instance.
        
        # Calculate float cost
        coords_ordered = coords[tour]
        coords_rolled = np.roll(coords_ordered, -1, axis=0)
        cost = np.linalg.norm(coords_ordered - coords_rolled, axis=1).sum()
        
        return cost

def get_dataset_hash(dataset):
    # Depending on how dataset is stored. tsp/utils.py just returns list of tensors?
    # load_val_dataset returns torch.load which is list of tensors usually if generated by utils.py
    # utils.py:
    # generates list of coords tensors.
    # torch.save(val_list, ...)
    # So dataset is a list of tensors (or just one tensor stacked?)
    # tsp/utils.py: load_val_dataset returns pack which is list of tensors? Or tensor?
    # tsp/train.py line 334: val_list = load_val_dataset(...)
    # line 255: for coords in tqdm(val_dataset...): -> implies it is iterable of coords
    
    hasher = hashlib.sha256()
    # Check if list or tensor
    if isinstance(dataset, list):
        for t in dataset:
            b = t.cpu().numpy().tobytes()
            hasher.update(b)
    elif isinstance(dataset, torch.Tensor):
         b = dataset.cpu().numpy().tobytes()
         hasher.update(b)
         
    return hasher.hexdigest()[:16]

def get_baseline_tsp(dataset, n_node, device="cpu", runs=1, time_limit=None):
    """
    Compute or load cached LKH baseline optimal values for the dataset.
    """
    this_dir = Path(__file__).parent.resolve()
    data_dir = (this_dir / "../data/tsp").resolve()
    
    if not data_dir.exists():
        data_dir.mkdir(parents=True, exist_ok=True)
        
    d_hash = get_dataset_hash(dataset)
    cache_file = data_dir / f"valDataset-{n_node}-{d_hash}-lkh.pt"
    
    if cache_file.exists():
        print(f"Loading LKH baseline from {cache_file}")
        data = torch.load(cache_file, map_location=device, weights_only=False)
        if isinstance(data, dict):
            costs = data["costs"]
            run_time = data["run_time"]
            print(f"Baseline run time: {run_time:.2f}s")
            return costs
        return data
    
    print(f"Computing LKH baseline for {len(dataset)} instances...")
    
    t_start = time.time()
    costs = []
    # If dataset is tensor (N, n_node, 2) or list of (n_node, 2)
    iterable = dataset
    
    for i, coords_t in enumerate(tqdm(iterable, desc="LKH Baseline")):
        if isinstance(coords_t, torch.Tensor):
            coords = coords_t.cpu().numpy()
        else:
            coords = coords_t
            
        c = solve_with_lkh(coords, runs=runs, time_limit=time_limit)
        costs.append(c)
    
    run_time = time.time() - t_start
    costs_t = torch.tensor(costs, dtype=torch.float32, device=device)
    torch.save({"costs": costs_t, "run_time": run_time}, cache_file)
    print(f"Saved LKH baseline to {cache_file} (run time: {run_time:.2f}s)")
    
    return costs_t
